### ISSUE TITLE
Cleaner msg about lack of Safari support

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-ledger-web-app#1]
Safari <v13 doesn't support u2f. But the error msg given is not clear about this: 

`TransportOpenUserCancelled: undefined is not an object (evaluating 'navigator.usb.getDevices')`
at

```
        async function getLedgerDevices() {
            // $FlowFixMe
            const devices = await navigator.usb.getDevices();  <<
```

**Comment by kobigurk** [comment]
Thanks, will add one!

I've checked a bit, and it seems none of the transports of ledgerjs support Safari at the moment.

I was thinking of another workaround, just to generate address - having the address displayed by default on the Ledger. Will that be helpful?
